language: java
jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: SioSPYThULrmSaK4HB3kjTuQPAFgI0LCJCRtHF9oNum6qSPVIcqyswehw2BLiUwZ9qYVgpH+hYHfC2CW19KXk47S3HZJX7IYLu+WnLiCoeuZZLCzc7FZJMwdjPWjwuYUu28ae2dBx/4fPj+qB4H6eWb3r7eWxLpsrgtF2O6MzKaA7ODDVKYxDzJxEaAqre024qNCF6GKhsza3WBtkhVt6R2B1eILWBTT4qg8DkM+ZrXojglriTG0+y0fKSuBnlgrJ3wft8arj5HVNMsbPxEiJ5QpcM/KAYxB+sOafOFE0vXH8XRsk/6RGobgSJI9BS5/dpGrRw8SVmvuDbZxC64e1a0RhYfz20wSk4zLoJ1ZWdpswU22Dd9WIvRmE1kpPfgD3wv5vCAgLIMHcOu3/FMDPJtjijU+vSKlFYaE5jOtUe31bYm2F23vmgc40SV408jAQJGEeNBs+j7UWLPzt1RrFqsito5+78BipNw9CG37q0XEouGBpBL1a7D9/2+Cv01W7oKvpJGldznxgXbWRpgWgj7ZnD0offWb64ofSLLlLgHV4RBd7d5XmeWYtsw4i+3PYdL0b0eyRiJMnPyRldwr39WSqRNJ3p9Aw14acSs+f2BUcIL9ls4oznJx6/zmrWmIIyy++kKEdUXo+MRxMignL6KDPOgR2UPuDDtDy8nLR+0=

